// Refresh content-addressed public resource URLs after editing local assets.
// Keeps GitHub Pages' cached HTML, code, styles and data from mixing releases.
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { root } from './server.mjs';
const hash = data => createHash('sha256').update(data).digest('hex').slice(0,12);
const files = ['data/bodies.json', ...(await readdir(path.join(root,'assets'))).filter(name=>/\.(jpg|png|webp|svg)$/.test(name)).map(name=>'assets/'+name)];
const versions = {};
for (const file of files.sort()) versions[file]=hash(await readFile(path.join(root,file)));
await writeFile(path.join(root,'src/asset-manifest.js'), `'use strict';\n// Generated by npm run version:assets.\nconst ATLAS_ASSET_VERSIONS = Object.freeze(${JSON.stringify(versions,null,2)});\n`);
let html=await readFile(path.join(root,'index.html'),'utf8');
for (const match of [...html.matchAll(/(?:src|href)="((?:src|vendor|assets)\/[^"?]+)(?:\?[^\"]*)?"/g)]) {
 const version=hash(await readFile(path.join(root,match[1])));
 html=html.replace(match[0],match[0].split('="')[0]+`="${match[1]}?v=${version}"`);
}
await writeFile(path.join(root,'index.html'),html);
console.log(`Versioned ${Object.keys(versions).length} image/data resources and public HTML references.`);
